config/routes.rb
Rails.application.routes.draw do
  resources :vestments
  resources :garments
  resources :garment_types
  resources :brands
  resources :emmisions
  resources :hosts
  devise_for :users

  root "brands#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/vestment.rb
class Vestment < ApplicationRecord
  belongs_to :emmision
  belongs_to :host
  belongs_to :garment
end

app/controllers/vestments_controller.rb
class VestmentsController < ApplicationController
  before_action :set_vestment, only: %i[ show edit update destroy ]

  # GET /vestments or /vestments.json
  def index
    @vestments = Vestment.all
    @vestments = @vestments.joins(:host).where(["first_name LIKE :filter OR last_name LIKE :filter", :filter => "%" + params[:filter] + "%"]) unless params[:filter].blank?
    @vestments = @vestments.joins(:garment).where([" description LIKE :filter2 ", :filter2 => "%" + params[:filter2] + "%"]) unless params[:filter2].blank?
    @vestments = @vestments.joins(:emmision).where([" number LIKE :filter3", :filter3 => "%" + params[:filter3] + "%"]) unless params[:filter3].blank?
  end






  # GET /vestments/1 or /vestments/1.json
  def show
  end

  # GET /vestments/new
  def new
    @vestment = Vestment.new
  end

  # GET /vestments/1/edit
  def edit
  end

  # POST /vestments or /vestments.json
  def create
    @vestment = Vestment.new(vestment_params)

    respond_to do |format|
      if @vestment.save
        format.html { redirect_to @vestment, notice: "Vestment was successfully created." }
        format.json { render :show, status: :created, location: @vestment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vestment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vestments/1 or /vestments/1.json
  def update
    respond_to do |format|
      if @vestment.update(vestment_params)
        format.html { redirect_to @vestment, notice: "Vestment was successfully updated." }
        format.json { render :show, status: :ok, location: @vestment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vestment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vestments/1 or /vestments/1.json
  def destroy
    @vestment.destroy
    respond_to do |format|
      format.html { redirect_to vestments_url, notice: "Vestment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vestment
      @vestment = Vestment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vestment_params
      params.require(:vestment).permit(:emmision_id, :host_id, :garment_id)
    end
end

app/helpers/vestments_helper.rb
module VestmentsHelper
end

app/views/vestments/_form.html.erb
<%= form_with(model: vestment) do |form| %>
  <% if vestment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vestment.errors.count, "error") %> prohibited this vestment from being saved:</h2>

      <ul>
        <% vestment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :emmision_id %>
    <%= form.collection_select(:emmision_id, Emmision.all, :id, :numberdate) %>
  </div>

  <div class="field">
    <%= form.label :host_id %>
    <%= form.collection_select(:host_id, Host.all, :id, :full_name) %>
  </div>

  <div class="field">
    <%= form.label :garment_id %>
    <%= form.collection_select(:garment_id, Garment.all, :id, :garmentdetails) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vestments/edit.html.erb
<h1>Editing Vestment</h1>

<%= render 'form', vestment: @vestment %>

<%= link_to 'Show', @vestment %> |
<%= link_to 'Back', vestments_path %>

app/views/vestments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vestments</h1>


<form method="GET" action="/vestments">
  Nombre o apellido del conductor: <input type="text" name="filter" />
  Descripcion: <input type="text" name="filter2" />
  Numero Transmision: <input type="text" name="filter3" />
  <input type="submit" />
</form>

<table>
  <thead>
    <tr>
      <th>Emmision</th>
      <th>Host</th>
      <th>Garment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vestments.each do |vestment| %>
      <tr>
        <td><%= vestment.emmision.number %></td>
        <td><%= vestment.host.full_name %></td>
        <td><%= vestment.garment.garmentdetails %></td>
        <td><%= link_to 'Show', vestment %></td>
        <td><%= link_to 'Edit', edit_vestment_path(vestment) %></td>
        <td><%= link_to 'Destroy', vestment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vestment', new_vestment_path %>

app/views/vestments/new.html.erb
<h1>New Vestment</h1>

<%= render 'form', vestment: @vestment %>

<%= link_to 'Back', vestments_path %>

app/views/vestments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Emmision:</strong>
  <%= @vestment.emmision_id %>
</p>

<p>
  <strong>Host:</strong>
  <%= @vestment.host_id %>
</p>

<p>
  <strong>Garment:</strong>
  <%= @vestment.garment_id %>
</p>

<%= link_to 'Edit', edit_vestment_path(@vestment) %> |
<%= link_to 'Back', vestments_path %>