config/routes.rb
Rails.application.routes.draw do
  resources :vestments
  resources :garments
  resources :garment_types
  resources :brands
  resources :emmisions
  resources :hosts
  devise_for :users

  root "brands#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/emmision.rb
class Emmision < ApplicationRecord
paginates_per 1
  def numberdate
  number

  has_many :vestments
end
end

app/controllers/emmisions_controller.rb
class EmmisionsController < ApplicationController
  before_action :set_emmision, only: %i[ show edit update destroy ]

  # GET /emmisions or /emmisions.json
  def index
    @emmisions = Emmision.all
    @emmisions = @emmisions.joins(:vestments).where(:vestments => {:vestment_id => params[:vestment_id]}) if params[:vestment_id]
    @emmisions = @emmisions.order(:number).page(params[:page] || 1)
  end

  # GET /emmisions/1 or /emmisions/1.json
  def show
  end

  # GET /emmisions/new
  def new
    @emmision = Emmision.new
  end

  # GET /emmisions/1/edit
  def edit
  end

  # POST /emmisions or /emmisions.json
  def create
    @emmision = Emmision.new(emmision_params)

    respond_to do |format|
      if @emmision.save
        format.html { redirect_to @emmision, notice: "Emmision was successfully created." }
        format.json { render :show, status: :created, location: @emmision }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @emmision.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emmisions/1 or /emmisions/1.json
  def update
    respond_to do |format|
      if @emmision.update(emmision_params)
        format.html { redirect_to @emmision, notice: "Emmision was successfully updated." }
        format.json { render :show, status: :ok, location: @emmision }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @emmision.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emmisions/1 or /emmisions/1.json
  def destroy
    @emmision.destroy
    respond_to do |format|
      format.html { redirect_to emmisions_url, notice: "Emmision was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emmision
      @emmision = Emmision.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def emmision_params
      params.require(:emmision).permit(:number, :date)
    end
end

app/helpers/emmisions_helper.rb
module EmmisionsHelper
end

app/views/emmisions/_form.html.erb
<%= form_with(model: emmision) do |form| %>
  <% if emmision.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(emmision.errors.count, "error") %> prohibited this emmision from being saved:</h2>

      <ul>
        <% emmision.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/emmisions/edit.html.erb
<h1>Editing Emmision</h1>

<%= render 'form', emmision: @emmision %>

<%= link_to 'Show', @emmision %> |
<%= link_to 'Back', emmisions_path %>

app/views/emmisions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Emmisions</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @emmisions.each do |emmision| %>
      <tr>
        <td><%= emmision.number %></td>
        <td><%= emmision.date %></td>
        <td><%= link_to 'Show', emmision %></td>
        <td><%= link_to 'Edit', edit_emmision_path(emmision) %></td>
        <td><%= link_to 'Destroy', emmision, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @emmisions %>
<br>

<%= link_to 'New Emmision', new_emmision_path %>

app/views/emmisions/new.html.erb
<h1>New Emmision</h1>

<%= render 'form', emmision: @emmision %>

<%= link_to 'Back', emmisions_path %>

app/views/emmisions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @emmision.number %>
</p>

<p>
  <strong>Date:</strong>
  <%= @emmision.date %>
</p>

<%= link_to 'Edit', edit_emmision_path(@emmision) %> |
<%= link_to 'Back', emmisions_path %>